platform :ios, '14.0'

target 'Runner' do
  use_frameworks!

  # Pods for Runner
  pod 'GoogleMaps', '~> 7.0'  # Ensure this matches the correct version
  pod 'GoogleMapsBase', '~> 7.0'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
